if(EXISTS "/Users/zypu/CLionProjects/design-patterns-in-modern-cpp/Creational/BuilderCodingExercise_UT[1]_tests.cmake")
  include("/Users/zypu/CLionProjects/design-patterns-in-modern-cpp/Creational/BuilderCodingExercise_UT[1]_tests.cmake")
else()
  add_test(BuilderCodingExercise_UT_NOT_BUILT BuilderCodingExercise_UT_NOT_BUILT)
endif()
